### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by yancyn** [yancyn/OutlookUrlAddIn#1]
Failed to install from release assembly (.vsto).

![image](https://user-images.githubusercontent.com/626925/27847925-b1892a6e-6173-11e7-915e-f2055431982e.png)

```
************** Exception Text **************
System.Security.SecurityException: Customized functionality in this application will not work because the certificate used to sign the deployment manifest for OutlookUrlAddIn or its location is not trusted. Contact your administrator for further assistance.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.ProcessSHA2Manifest(ActivationContext context, DeploymentSignatureInformation signatureInformation, PermissionSet permissionsRequested, Uri manifest, ManifestSignatureInformationCollection signatures, AddInInstallationStatus installState, TrustStatus sha256TrustStatus, X509Certificate2 sha256PublisherCert)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
The Zone of the assembly that failed was:
```

**Comment by yancyn** [comment]
## Overwrite Publisher Value
1. Start ```mage``` from Visual Studio command prompt.
2. Open *.manifest file to modify _Publisher_ value. Then save and sign with certificate.
3. Open *.vsto file to modify _Publisher_ value then sign with certificate. Then save and sign with certificate.
4. Done.

see https://blogs.msdn.microsoft.com/vsto/2008/06/11/specifying-a-product-name-publisher-name-and-other-properties-for-vsto-solutions-saurabh-bhatia/

**Comment by yancyn** [comment]
Please download [v0.1.0.8](https://github.com/yancyn/OutlookUrlAddIn/releases/tag/v0.1.0.8) under release tab. This should solve the publisher issue.

**Comment by yancyn** [comment]
Zip the assemblies then only upload to github. Everything looks fine now. But if upload all the assemblies one by one then download again that cause the certificate or location not trusted.

Confirm checksum for both files are same by comparing original assemblies with download from github. So what else possible the cause?
